[[redirects]]
  from = "/skills/*"
  to = "/skills/index.html"
  status = 200

[[redirects]]
  from = "/projects/*"
  to = "/projects/index.html"
  status = 200

[[redirects]]
  from = "/contact/*"
  to = "/contact/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
